platform :ios, '8.0'

target 'RCTAMapExample' do

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native', :subspecs => [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'AMap3DMap-NO-IDFA', '4.6.0'
  pod 'AMapNavi-NO-IDFA'
  pod 'react-native-amap', path: '../../'

end